AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for AWS Translate demo with S3 + IAM

Resources:
  # --------- S3 Buckets ---------
  RequestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-request-bucket"
      VersioningConfiguration: { Status: Enabled }
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldFiles
            Status: Enabled
            ExpirationInDays: 7

  ResponseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-response-bucket"
      VersioningConfiguration: { Status: Enabled }
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldFiles
            Status: Enabled
            ExpirationInDays: 7

  # --------- IAM Role for Lambda (S3 + Translate) ---------
  TranslateS3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "TranslateS3Role-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: [ "lambda.amazonaws.com" ] }
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  TranslateS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TranslateS3AccessPolicy
      Roles: [ !Ref TranslateS3Role ]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: [ "translate:TranslateText" ]
            Resource: "*"
          - Effect: Allow
            Action: [ "s3:GetObject", "s3:PutObject", "s3:ListBucket" ]
            Resource:
              - !Sub "arn:aws:s3:::${AWS::AccountId}-request-bucket"
              - !Sub "arn:aws:s3:::${AWS::AccountId}-request-bucket/*"
              - !Sub "arn:aws:s3:::${AWS::AccountId}-response-bucket"
              - !Sub "arn:aws:s3:::${AWS::AccountId}-response-bucket/*"

Outputs:
  RequestBucketName:
    Description: S3 bucket for input files
    Value: !Ref RequestBucket
  ResponseBucketName:
    Description: S3 bucket for translated output
    Value: !Ref ResponseBucket
  TranslateS3RoleArn:
    Description: IAM Role ARN with Translate + S3 + Logs
    Value: !GetAtt TranslateS3Role.Arn
